/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.glb --types
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Boat: THREE.Mesh
    Upper: THREE.Mesh
    Pier: THREE.Mesh
    Base: THREE.Mesh
    Columns: THREE.Mesh
    Land: THREE.Mesh
    Road: THREE.Mesh
    Sea: THREE.Mesh
    Boat_cutter: THREE.Mesh
    Cone: THREE.Mesh
    Rock014: THREE.Mesh
    Rock001: THREE.Mesh
    Rock002: THREE.Mesh
    Rock003: THREE.Mesh
    Rock004: THREE.Mesh
    Rock005: THREE.Mesh
    Rock006: THREE.Mesh
    Rock007: THREE.Mesh
    Rock008: THREE.Mesh
    Rock009: THREE.Mesh
    Rock010: THREE.Mesh
    Rock011: THREE.Mesh
    Rock012: THREE.Mesh
    Rock013: THREE.Mesh
    Tower: THREE.Mesh
    Tower_1: THREE.Mesh
    Tower_2: THREE.Mesh
    Tower_3: THREE.Mesh
    Tower_4: THREE.Mesh
    Base001: THREE.Mesh
  }
  materials: {
    ['Wood light']: THREE.MeshStandardMaterial
    Earth: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    Sea: THREE.MeshPhysicalMaterial
    ['Wood light.001']: THREE.MeshStandardMaterial
    Lightcone: THREE.MeshStandardMaterial
    Rock: THREE.MeshStandardMaterial
    ['Lighthouse white']: THREE.MeshStandardMaterial
    ['Lighthouse red']: THREE.MeshStandardMaterial
    Window: THREE.MeshStandardMaterial
    Roof: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Boat.geometry} material={materials['Wood light']}>
        <mesh geometry={nodes.Upper.geometry} material={materials['Wood light']} position={[2.932, 1.189, -0.72]} scale={[0.058, 0.231, 0.15]} />
      </mesh>
      <mesh geometry={nodes.Pier.geometry} material={materials['Wood light']}>
        <mesh geometry={nodes.Base.geometry} material={materials['Wood light']} position={[0.985, 1.32, -0.129]} scale={[0.296, 0.296, 0.03]} />
        <mesh geometry={nodes.Columns.geometry} material={materials['Wood light']} position={[1.2, 1.32, -0.129]} scale={[0.037, 0.074, 0.037]} />
      </mesh>
      <mesh geometry={nodes.Land.geometry} material={materials.Earth} />
      <mesh geometry={nodes.Road.geometry} material={materials.Road} />
      <mesh geometry={nodes.Sea.geometry} material={materials.Sea} position={[0.002, 0, 0]} scale={[0.998, 1, 0.998]} />
      <mesh geometry={nodes.Boat_cutter.geometry} material={materials['Wood light.001']} />
      <mesh geometry={nodes.Cone.geometry} material={materials.Lightcone} position={[-0.173, 4.835, -1.606]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[1, 2.807, 1]} />
      <mesh geometry={nodes.Rock014.geometry} material={materials.Rock} position={[-3.233, 1.54, 1.568]} rotation={[0.381, -0.074, -0.324]} scale={0.153} />
      <mesh geometry={nodes.Rock001.geometry} material={materials.Rock} position={[0.733, 1.036, -3.732]} scale={0.153} />
      <mesh geometry={nodes.Rock002.geometry} material={materials.Rock} position={[1.3, 1.036, -3.499]} rotation={[2.703, 0.444, 0.829]} scale={0.071} />
      <mesh geometry={nodes.Rock003.geometry} material={materials.Rock} position={[3.444, 0.811, 2.155]} rotation={[-0.086, -0.085, 1.803]} scale={0.153} />
      <mesh geometry={nodes.Rock004.geometry} material={materials.Rock} position={[1.87, 1.497, 2.89]} rotation={[0.043, 0.394, -2.883]} scale={0.153} />
      <mesh geometry={nodes.Rock005.geometry} material={materials.Rock} position={[-2.364, 1.62, 2.307]} rotation={[-0.012, 0.007, -0.309]} scale={0.165} />
      <mesh geometry={nodes.Rock006.geometry} material={materials.Rock} position={[1.22, 1.09, -3.82]} rotation={[0.036, 0.001, 0.055]} scale={0.102} />
      <mesh geometry={nodes.Rock007.geometry} material={materials.Rock} position={[0.749, 1.03, -3.336]} rotation={[0.036, 0.001, 0.055]} scale={0.101} />
      <mesh geometry={nodes.Rock008.geometry} material={materials.Rock} position={[2.26, 1.495, 2.417]} rotation={[-0.026, 0.009, 0.038]} scale={0.12} />
      <mesh geometry={nodes.Rock009.geometry} material={materials.Rock} position={[3.185, 0.807, 3.745]} rotation={[1.516, 0, 1.574]} scale={0.133} />
      <mesh geometry={nodes.Rock010.geometry} material={materials.Rock} position={[-3.49, 1.561, 1.072]} rotation={[-0.214, -0.013, 0.072]} scale={[0.403, 0.134, 0.134]} />
      <mesh geometry={nodes.Rock011.geometry} material={materials.Rock} position={[3.311, 0.816, 1.676]} rotation={[0.038, -0.294, -1.187]} scale={[0.403, 0.134, 0.134]} />
      <mesh geometry={nodes.Rock012.geometry} material={materials.Rock} position={[1.138, 1.058, -3.316]} rotation={[-0.157, -0.355, -0.279]} scale={[0.212, 0.071, 0.071]} />
      <mesh geometry={nodes.Rock013.geometry} material={materials.Rock} position={[1.79, 1.483, 2.439]} rotation={[-3.018, 1.174, 3.13]} scale={[0.315, 0.105, 0.105]} />
      <group position={[-0.192, 1.371, -1.606]}>
        <mesh name="Tower" geometry={nodes.Tower.geometry} material={materials['Lighthouse white']} morphTargetDictionary={nodes.Tower.morphTargetDictionary} morphTargetInfluences={nodes.Tower.morphTargetInfluences} />
        <mesh name="Tower_1" geometry={nodes.Tower_1.geometry} material={materials['Lighthouse red']} morphTargetDictionary={nodes.Tower_1.morphTargetDictionary} morphTargetInfluences={nodes.Tower_1.morphTargetInfluences} />
        <mesh name="Tower_2" geometry={nodes.Tower_2.geometry} material={materials.Window} morphTargetDictionary={nodes.Tower_2.morphTargetDictionary} morphTargetInfluences={nodes.Tower_2.morphTargetInfluences} />
        <mesh name="Tower_3" geometry={nodes.Tower_3.geometry} material={materials.Roof} morphTargetDictionary={nodes.Tower_3.morphTargetDictionary} morphTargetInfluences={nodes.Tower_3.morphTargetInfluences} />
        <mesh name="Tower_4" geometry={nodes.Tower_4.geometry} material={materials.Wood} morphTargetDictionary={nodes.Tower_4.morphTargetDictionary} morphTargetInfluences={nodes.Tower_4.morphTargetInfluences} />
        <mesh name="Base001" geometry={nodes.Base001.geometry} material={materials['Lighthouse white']} morphTargetDictionary={nodes.Base001.morphTargetDictionary} morphTargetInfluences={nodes.Base001.morphTargetInfluences} position={[0, 0.439, 0]} scale={[0.724, 0.199, 0.724]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
